spring.application.name=movieTracker
spring.datasource.url=jdbc:mysql://localhost:3308/springbootdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configuracion API OMDb
omdb.api.key=aad86a3
omdb.api.url=http://www.omdbapi.com/

# Configuracion OpenRouter para el chatbot de IA
openrouter.api.key=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
openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.model=mistralai/devstral-2512:free
